# Generated by Django 4.2.2 on 2025-10-10 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_alter_record_client_delete_client"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="slot",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="client.slot",
                verbose_name="Слот",
            ),
        ),
    ]
