# Generated by Django 4.2.2 on 2025-10-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_alter_record_slot"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="slot",
            constraint=models.UniqueConstraint(
                fields=("doctor", "start_time"), name="unique_doctor_start_time"
            ),
        ),
    ]
