# Generated by Django 4.2.2 on 2025-10-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="picture",
            field=models.ImageField(
                blank=True,
                default="img_7.png",
                upload_to="services/picture",
                verbose_name="Картинка",
            ),
        ),
    ]
