# Generated by Django 4.2.2 on 2025-10-12 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_alter_service_picture"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "ordering": ["name"],
                "permissions": [("can_manage_services", "Может управлять услугами")],
                "verbose_name": "Услуга",
                "verbose_name_plural": "Услуги",
            },
        ),
    ]
