# Generated by Django 4.2.2 on 2025-09-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=50, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Отчество"
                    ),
                ),
                (
                    "education",
                    models.CharField(max_length=300, verbose_name="Образование"),
                ),
                (
                    "specialization",
                    models.CharField(max_length=100, verbose_name="Специализация"),
                ),
                ("experience", models.TextField(verbose_name="Опыт работы")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, upload_to="doctor/photo", verbose_name="Фото врача"
                    ),
                ),
            ],
            options={
                "verbose_name": "Доктор",
                "verbose_name_plural": "Доктора",
                "ordering": ["last_name"],
            },
        ),
    ]
