# Generated by Django 4.2.2 on 2025-10-09 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="avatar",
            field=models.ImageField(
                blank=True,
                default="img_6.png",
                upload_to="doctor/photo",
                verbose_name="Фото врача",
            ),
        ),
    ]
