# Generated by Django 4.2.2 on 2025-10-12 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctors", "0002_alter_doctor_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="doctor",
            options={
                "ordering": ["last_name"],
                "permissions": [("can_manage_doctors", "Может управлять врачами")],
                "verbose_name": "Доктор",
                "verbose_name_plural": "Доктора",
            },
        ),
    ]
